import SwiftUI

enum MaterialIcons {
    struct Spec: Sendable { let asset: String; let mirrored: Bool }

    static let map: [String: Spec] = [
        "AutoMirrored.Filled.ArrowBack": Spec(asset: "filled.arrow_back", mirrored: true),
        "AutoMirrored.Filled.ArrowBackIos": Spec(asset: "filled.arrow_back_ios", mirrored: true),
        "AutoMirrored.Filled.ArrowForward": Spec(asset: "filled.arrow_forward", mirrored: true),
        "AutoMirrored.Filled.ArrowForwardIos": Spec(asset: "filled.arrow_forward_ios", mirrored: true),
        "AutoMirrored.Filled.Article": Spec(asset: "filled.article", mirrored: true),
        "AutoMirrored.Filled.Assignment": Spec(asset: "filled.assignment", mirrored: true),
        "AutoMirrored.Filled.Chat": Spec(asset: "filled.chat", mirrored: true),
        "AutoMirrored.Filled.EventNote": Spec(asset: "filled.event_note", mirrored: true),
        "AutoMirrored.Filled.HelpOutline": Spec(asset: "filled.help_outline", mirrored: true),
        "AutoMirrored.Filled.InsertDriveFile": Spec(asset: "filled.insert_drive_file", mirrored: true),
        "AutoMirrored.Filled.KeyboardArrowLeft": Spec(asset: "filled.keyboard_arrow_left", mirrored: true),
        "AutoMirrored.Filled.KeyboardArrowRight": Spec(asset: "filled.keyboard_arrow_right", mirrored: true),
        "AutoMirrored.Filled.LibraryBooks": Spec(asset: "filled.library_books", mirrored: true),
        "AutoMirrored.Filled.ListAlt": Spec(asset: "filled.list_alt", mirrored: true),
        "AutoMirrored.Filled.Logout": Spec(asset: "filled.logout", mirrored: true),
        "AutoMirrored.Filled.MenuBook": Spec(asset: "filled.menu_book", mirrored: true),
        "AutoMirrored.Filled.OpenInNew": Spec(asset: "filled.open_in_new", mirrored: true),
        "AutoMirrored.Filled.Reply": Spec(asset: "filled.reply", mirrored: true),
        "AutoMirrored.Filled.TrendingUp": Spec(asset: "filled.trending_up", mirrored: true),
        "AutoMirrored.Filled.Undo": Spec(asset: "filled.undo", mirrored: true),
        "AutoMirrored.Outlined.Article": Spec(asset: "outlined.article", mirrored: true),
        "AutoMirrored.Outlined.Chat": Spec(asset: "outlined.chat", mirrored: true),
        "AutoMirrored.Outlined.HelpOutline": Spec(asset: "outlined.help_outline", mirrored: true),
        "AutoMirrored.Outlined.LibraryBooks": Spec(asset: "outlined.library_books", mirrored: true),
        "Filled.AccessTime": Spec(asset: "filled.access_time", mirrored: false),
        "Filled.AccountBalance": Spec(asset: "filled.account_balance", mirrored: false),
        "Filled.AccountCircle": Spec(asset: "filled.account_circle", mirrored: false),
        "Filled.Add": Spec(asset: "filled.add", mirrored: false),
        "Filled.AddCircle": Spec(asset: "filled.add_circle", mirrored: false),
        "Filled.AddComment": Spec(asset: "filled.add_comment", mirrored: false),
        "Filled.AdminPanelSettings": Spec(asset: "filled.admin_panel_settings", mirrored: false),
        "Filled.Analytics": Spec(asset: "filled.analytics", mirrored: false),
        "Filled.ArrowDownward": Spec(asset: "filled.arrow_downward", mirrored: false),
        "Filled.ArrowUpward": Spec(asset: "filled.arrow_upward", mirrored: false),
        "Filled.Assessment": Spec(asset: "filled.assessment", mirrored: false),
        "Filled.Audiotrack": Spec(asset: "filled.audiotrack", mirrored: false),
        "Filled.Backpack": Spec(asset: "filled.backpack", mirrored: false),
        "Filled.Badge": Spec(asset: "filled.badge", mirrored: false),
        "Filled.BarChart": Spec(asset: "filled.bar_chart", mirrored: false),
        "Filled.Block": Spec(asset: "filled.block", mirrored: false),
        "Filled.Brush": Spec(asset: "filled.brush", mirrored: false),
        "Filled.Calculate": Spec(asset: "filled.calculate", mirrored: false),
        "Filled.CalendarMonth": Spec(asset: "filled.calendar_month", mirrored: false),
        "Filled.Call": Spec(asset: "filled.call", mirrored: false),
        "Filled.CameraAlt": Spec(asset: "filled.camera_alt", mirrored: false),
        "Filled.Campaign": Spec(asset: "filled.campaign", mirrored: false),
        "Filled.Cancel": Spec(asset: "filled.cancel", mirrored: false),
        "Filled.Category": Spec(asset: "filled.category", mirrored: false),
        "Filled.Celebration": Spec(asset: "filled.celebration", mirrored: false),
        "Filled.Check": Spec(asset: "filled.check", mirrored: false),
        "Filled.CheckCircle": Spec(asset: "filled.check_circle", mirrored: false),
        "Filled.Class": Spec(asset: "filled.class", mirrored: false),
        "Filled.Close": Spec(asset: "filled.close", mirrored: false),
        "Filled.CloudOff": Spec(asset: "filled.cloud_off", mirrored: false),
        "Filled.Coffee": Spec(asset: "filled.coffee", mirrored: false),
        "Filled.ContentCopy": Spec(asset: "filled.content_copy", mirrored: false),
        "Filled.Delete": Spec(asset: "filled.delete", mirrored: false),
        "Filled.DeleteOutline": Spec(asset: "filled.delete_outline", mirrored: false),
        "Filled.Description": Spec(asset: "filled.description", mirrored: false),
        "Filled.DirectionsBus": Spec(asset: "filled.directions_bus", mirrored: false),
        "Filled.DoneAll": Spec(asset: "filled.done_all", mirrored: false),
        "Filled.Download": Spec(asset: "filled.download", mirrored: false),
        "Filled.Drafts": Spec(asset: "filled.drafts", mirrored: false),
        "Filled.Edit": Spec(asset: "filled.edit", mirrored: false),
        "Filled.EditCalendar": Spec(asset: "filled.edit_calendar", mirrored: false),
        "Filled.EditNote": Spec(asset: "filled.edit_note", mirrored: false),
        "Filled.Emergency": Spec(asset: "filled.emergency", mirrored: false),
        "Filled.Error": Spec(asset: "filled.error", mirrored: false),
        "Filled.ErrorOutline": Spec(asset: "filled.error_outline", mirrored: false),
        "Filled.EventAvailable": Spec(asset: "filled.event_available", mirrored: false),
        "Filled.EventBusy": Spec(asset: "filled.event_busy", mirrored: false),
        "Filled.ExpandMore": Spec(asset: "filled.expand_more", mirrored: false),
        "Filled.Face": Spec(asset: "filled.face", mirrored: false),
        "Filled.FamilyRestroom": Spec(asset: "filled.family_restroom", mirrored: false),
        "Filled.Favorite": Spec(asset: "filled.favorite", mirrored: false),
        "Filled.Flag": Spec(asset: "filled.flag", mirrored: false),
        "Filled.FlashlightOff": Spec(asset: "filled.flashlight_off", mirrored: false),
        "Filled.FlashlightOn": Spec(asset: "filled.flashlight_on", mirrored: false),
        "Filled.Forum": Spec(asset: "filled.forum", mirrored: false),
        "Filled.Grade": Spec(asset: "filled.grade", mirrored: false),
        "Filled.Groups": Spec(asset: "filled.groups", mirrored: false),
        "Filled.HelpOutline": Spec(asset: "filled.help_outline", mirrored: false),
        "Filled.Home": Spec(asset: "filled.home", mirrored: false),
        "Filled.HourglassEmpty": Spec(asset: "filled.hourglass_empty", mirrored: false),
        "Filled.HowToReg": Spec(asset: "filled.how_to_reg", mirrored: false),
        "Filled.Image": Spec(asset: "filled.image", mirrored: false),
        "Filled.Insights": Spec(asset: "filled.insights", mirrored: false),
        "Filled.Inventory2": Spec(asset: "filled.inventory_2", mirrored: false),
        "Filled.IosShare": Spec(asset: "filled.ios_share", mirrored: false),
        "Filled.Keyboard": Spec(asset: "filled.keyboard", mirrored: false),
        "Filled.KeyboardArrowDown": Spec(asset: "filled.keyboard_arrow_down", mirrored: false),
        "Filled.Language": Spec(asset: "filled.language", mirrored: false),
        "Filled.LinkOff": Spec(asset: "filled.link_off", mirrored: false),
        "Filled.LocalCafe": Spec(asset: "filled.local_cafe", mirrored: false),
        "Filled.LocalFireDepartment": Spec(asset: "filled.local_fire_department", mirrored: false),
        "Filled.Lock": Spec(asset: "filled.lock", mirrored: false),
        "Filled.Mail": Spec(asset: "filled.mail", mirrored: false),
        "Filled.MailOutline": Spec(asset: "filled.mail_outline", mirrored: false),
        "Filled.MarkEmailUnread": Spec(asset: "filled.mark_email_unread", mirrored: false),
        "Filled.MedicalServices": Spec(asset: "filled.medical_services", mirrored: false),
        "Filled.Mic": Spec(asset: "filled.mic", mirrored: false),
        "Filled.MoreHoriz": Spec(asset: "filled.more_horiz", mirrored: false),
        "Filled.Notifications": Spec(asset: "filled.notifications", mirrored: false),
        "Filled.NotificationsActive": Spec(asset: "filled.notifications_active", mirrored: false),
        "Filled.NotificationsOff": Spec(asset: "filled.notifications_off", mirrored: false),
        "Filled.Pause": Spec(asset: "filled.pause", mirrored: false),
        "Filled.PendingActions": Spec(asset: "filled.pending_actions", mirrored: false),
        "Filled.People": Spec(asset: "filled.people", mirrored: false),
        "Filled.PeopleOutline": Spec(asset: "filled.people_outline", mirrored: false),
        "Filled.Person": Spec(asset: "filled.person", mirrored: false),
        "Filled.PersonAdd": Spec(asset: "filled.person_add", mirrored: false),
        "Filled.PersonOff": Spec(asset: "filled.person_off", mirrored: false),
        "Filled.Phone": Spec(asset: "filled.phone", mirrored: false),
        "Filled.Photo": Spec(asset: "filled.photo", mirrored: false),
        "Filled.PhotoCamera": Spec(asset: "filled.photo_camera", mirrored: false),
        "Filled.PictureAsPdf": Spec(asset: "filled.picture_as_pdf", mirrored: false),
        "Filled.Place": Spec(asset: "filled.place", mirrored: false),
        "Filled.PlayArrow": Spec(asset: "filled.play_arrow", mirrored: false),
        "Filled.PostAdd": Spec(asset: "filled.post_add", mirrored: false),
        "Filled.PriorityHigh": Spec(asset: "filled.priority_high", mirrored: false),
        "Filled.Public": Spec(asset: "filled.public", mirrored: false),
        "Filled.PushPin": Spec(asset: "filled.push_pin", mirrored: false),
        "Filled.QrCode2": Spec(asset: "filled.qr_code_2", mirrored: false),
        "Filled.QrCodeScanner": Spec(asset: "filled.qr_code_scanner", mirrored: false),
        "Filled.QueryStats": Spec(asset: "filled.query_stats", mirrored: false),
        "Filled.QuestionMark": Spec(asset: "filled.question_mark", mirrored: false),
        "Filled.Quiz": Spec(asset: "filled.quiz", mirrored: false),
        "Filled.RateReview": Spec(asset: "filled.rate_review", mirrored: false),
        "Filled.Refresh": Spec(asset: "filled.refresh", mirrored: false),
        "Filled.Remove": Spec(asset: "filled.remove", mirrored: false),
        "Filled.Schedule": Spec(asset: "filled.schedule", mirrored: false),
        "Filled.School": Spec(asset: "filled.school", mirrored: false),
        "Filled.Science": Spec(asset: "filled.science", mirrored: false),
        "Filled.Search": Spec(asset: "filled.search", mirrored: false),
        "Filled.SearchOff": Spec(asset: "filled.search_off", mirrored: false),
        "Filled.SentimentDissatisfied": Spec(asset: "filled.sentiment_dissatisfied", mirrored: false),
        "Filled.SentimentVeryDissatisfied": Spec(asset: "filled.sentiment_very_dissatisfied", mirrored: false),
        "Filled.SentimentVerySatisfied": Spec(asset: "filled.sentiment_very_satisfied", mirrored: false),
        "Filled.Spellcheck": Spec(asset: "filled.spellcheck", mirrored: false),
        "Filled.SportsSoccer": Spec(asset: "filled.sports_soccer", mirrored: false),
        "Filled.Star": Spec(asset: "filled.star", mirrored: false),
        "Filled.StarBorder": Spec(asset: "filled.star_border", mirrored: false),
        "Filled.StarOutline": Spec(asset: "filled.star_outline", mirrored: false),
        "Filled.Storage": Spec(asset: "filled.storage", mirrored: false),
        "Filled.Summarize": Spec(asset: "filled.summarize", mirrored: false),
        "Filled.ThumbDown": Spec(asset: "filled.thumb_down", mirrored: false),
        "Filled.ThumbUp": Spec(asset: "filled.thumb_up", mirrored: false),
        "Filled.Today": Spec(asset: "filled.today", mirrored: false),
        "Filled.TouchApp": Spec(asset: "filled.touch_app", mirrored: false),
        "Filled.Translate": Spec(asset: "filled.translate", mirrored: false),
        "Filled.VerifiedUser": Spec(asset: "filled.verified_user", mirrored: false),
        "Filled.Videocam": Spec(asset: "filled.videocam", mirrored: false),
        "Filled.VisibilityOff": Spec(asset: "filled.visibility_off", mirrored: false),
        "Filled.WavingHand": Spec(asset: "filled.waving_hand", mirrored: false),
        "Filled.WbSunny": Spec(asset: "filled.wb_sunny", mirrored: false),
        "Filled.WbTwilight": Spec(asset: "filled.wb_twilight", mirrored: false),
        "Filled.WorkspacePremium": Spec(asset: "filled.workspace_premium", mirrored: false),
        "Outlined.AccountCircle": Spec(asset: "outlined.account_circle", mirrored: false),
        "Outlined.AddCircle": Spec(asset: "outlined.add_circle", mirrored: false),
        "Outlined.Badge": Spec(asset: "outlined.badge", mirrored: false),
        "Outlined.BarChart": Spec(asset: "outlined.bar_chart", mirrored: false),
        "Outlined.CalendarMonth": Spec(asset: "outlined.calendar_month", mirrored: false),
        "Outlined.Campaign": Spec(asset: "outlined.campaign", mirrored: false),
        "Outlined.ChatBubbleOutline": Spec(asset: "outlined.chat_bubble_outline", mirrored: false),
        "Outlined.Circle": Spec(asset: "outlined.circle", mirrored: false),
        "Outlined.Class": Spec(asset: "outlined.class", mirrored: false),
        "Outlined.DarkMode": Spec(asset: "outlined.dark_mode", mirrored: false),
        "Outlined.Description": Spec(asset: "outlined.description", mirrored: false),
        "Outlined.ErrorOutline": Spec(asset: "outlined.error_outline", mirrored: false),
        "Outlined.FactCheck": Spec(asset: "outlined.fact_check", mirrored: false),
        "Outlined.Fingerprint": Spec(asset: "outlined.fingerprint", mirrored: false),
        "Outlined.Grade": Spec(asset: "outlined.grade", mirrored: false),
        "Outlined.Groups": Spec(asset: "outlined.groups", mirrored: false),
        "Outlined.Home": Spec(asset: "outlined.home", mirrored: false),
        "Outlined.Language": Spec(asset: "outlined.language", mirrored: false),
        "Outlined.LightMode": Spec(asset: "outlined.light_mode", mirrored: false),
        "Outlined.Lock": Spec(asset: "outlined.lock", mirrored: false),
        "Outlined.MoreHoriz": Spec(asset: "outlined.more_horiz", mirrored: false),
        "Outlined.Notifications": Spec(asset: "outlined.notifications", mirrored: false),
        "Outlined.People": Spec(asset: "outlined.people", mirrored: false),
        "Outlined.Person": Spec(asset: "outlined.person", mirrored: false),
        "Outlined.PushPin": Spec(asset: "outlined.push_pin", mirrored: false),
        "Outlined.School": Spec(asset: "outlined.school", mirrored: false),
        "Outlined.Search": Spec(asset: "outlined.search", mirrored: false),
        "Outlined.Settings": Spec(asset: "outlined.settings", mirrored: false),
        "Outlined.Shield": Spec(asset: "outlined.shield", mirrored: false),
        "Outlined.VolumeUp": Spec(asset: "outlined.volume_up", mirrored: false),
        "Outlined.WorkspacePremium": Spec(asset: "outlined.workspace_premium", mirrored: false),
    ]
}

struct MaterialIcon: View {
    let name: String
    var size: CGFloat = 24

    init(_ name: String, size: CGFloat = 24) {
        self.name = name
        self.size = size
    }

    var body: some View {
        let spec = MaterialIcons.map[name]
        Image(spec?.asset ?? "filled.help_outline")
            .renderingMode(.template)
            .resizable()
            .scaledToFit()
            .frame(width: size, height: size)
            .flipsForRightToLeftLayoutDirection(spec?.mirrored ?? false)
            .accessibilityHidden(true)
    }
}
